/**
 * ParticleFX - tiny burst emitter used when a match finishes clearing.
 *
 * NOTE on placement: this file lives under engine/ per the visual-polish
 * spec, but it intentionally depends on Phaser. Unlike the rest of the
 * engine, it is presentation-only and never imported by any logic module
 * or by engine/index.ts. Vitest only collects tests-spec files, so the
 * Phaser dependency stays out of unit tests.
 *
 * One particle emitter is cached per scene (lazy init). Each call to
 * spawnClearBurst emits 3-5 short-lived 4x4 pixels at the requested point,
 * tinted by the cleared block color. The pixel texture is generated by
 * PreloadScene.
 */

import Phaser from 'phaser';

// Per-scene cached emitter. Using a WeakMap keeps the reference alive only
// while the scene is alive and lets us avoid annotating Phaser.Scene with a
// custom symbol-keyed field (which trips the parser in some TS configs).
const emitterByScene = new WeakMap<Phaser.Scene, Phaser.GameObjects.Particles.ParticleEmitter>();

function getEmitter(
  scene: Phaser.Scene,
): Phaser.GameObjects.Particles.ParticleEmitter | null {
  const cached = emitterByScene.get(scene);
  if (cached && cached.active) return cached;

  // Texture might not exist if PreloadScene hasn't run (e.g. early test
  // harness); fail soft in that case.
  if (!scene.textures.exists('pixel')) return null;

  const emitter = scene.add.particles(0, 0, 'pixel', {
    lifespan: 380,
    speed: { min: 40, max: 110 },
    angle: { min: 0, max: 360 },
    scale: { start: 1.4, end: 0 },
    alpha: { start: 1, end: 0 },
    gravityY: 160,
    rotate: { min: 0, max: 360 },
    emitting: false,
  });
  emitter.setDepth(9_000);

  emitterByScene.set(scene, emitter);

  const teardown = (): void => {
    emitter.destroy();
    emitterByScene.delete(scene);
  };
  scene.events.once(Phaser.Scenes.Events.SHUTDOWN, teardown);
  scene.events.once(Phaser.Scenes.Events.DESTROY, teardown);
  return emitter;
}

/**
 * Spawns 3-5 colored pixel sparks at (x, y). Color is an integer hex tint;
 * callers typically pass BLOCK_COLOR_HEX[block.color].
 */
export function spawnClearBurst(
  scene: Phaser.Scene,
  x: number,
  y: number,
  color: number,
): void {
  const emitter = getEmitter(scene);
  if (!emitter) return;
  const count = 3 + Math.floor(Math.random() * 3); // 3..5
  emitter.setParticleTint(color);
  emitter.emitParticleAt(x, y, count);
}
